name: cdk

on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"

      - name: Setup dependencies
        run: cd cdk && npm ci

      - name: Build
        run: npm run build

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk:diff
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy Dev
        if: contains(github.event_name, 'push')
        run: npm run cdk:deploy-dev
        env:
          AWS_DEFAULT_REGION: "ap-northeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
